kakao:
    rest-api:
      blog:
        baseurl: https://dapi.kakao.com/v2/search/blog
        token: ${KAKAO_REST_API_TOKEN}

naver:
  rest-api:
    blog:
      baseurl: https://openapi.naver.com/v1/search/blog.json
      clientid: ${NAVER_CLIENT_ID}
      clientsecret: ${NAVER_CLIENT_SECRET}

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true


